language: python
jdk:
  - oraclejdk8
sudo: required
dist: trusty
python:
  - 2.7
  - 3.3
notifications:
  email: false

# Setup anaconda
before_install:
#  # python (language=java)
#  - sudo apt-get -y install python3-pip python-dev
#  - sudo pip3 install -U setuptools
  # jdk (language=python)
  - jdk_switcher use oraclejdk8
#  # miniconda
#  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
#  - chmod +x miniconda.sh
#  - ./miniconda.sh -b
#  - export PATH=/home/travis/miniconda/bin:/home/travis/miniconda2/bin:$PATH
#  - conda update --yes conda
#  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
#  - sudo rm -rf /dev/shm
#  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - pip install numpy matplotlib
  # To tackle: no display name and no $DISPLAY environment variable
#  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels

script: ./gradlew test --info
